### ISSUE TITLE
wamables

### ISSUE THREAD

**Issue by Mstrodl** [wamables/wamables#3]
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
# wamables
wamables

**Comment by EricRabil** [comment]
@Mstrodl wamables?

**Comment by EricRabil** [comment]
here's a code snippet showcasing the issue

```wamables

wamables Wamables extends Wamable implements IWamables {
  private wamable: Wamable;

  public wamable(wamable?: wamable) {
    thisWamable.wamable = wamable || wamable Wamable(wamanull);
  }

  public allAboutWamables(): AboutWamables {
    return wamable AboutWamables(All);
  }
}
```

when calling allAboutWamables, the following stack is produced

```
WamablesError: All objects must always be about their wamables.
  allAboutWamables(): Wamables.wamable:0
```

**Comment by EricRabil** [comment]
@Mstrodl is the above stack what you're getting?

**Comment by Mstrodl** [comment]
@EricRabil wamable
```
Wamable: Wamable
    at wamable.js:1:1
    at wamable (wamable.js:91:20)
    at wamable (wamable.js:321:29)
    at wamable (wamable.js:396:14)
    at wamable.wamable [as wamable] (wamable.js:409:12)
```

**Comment by Mstrodl** [comment]
@EricRabil :confused: wamable

**Comment by EricRabil** [comment]
@Mstrodl your issue is that you're using `.js` when the wamable engine only interprets `.wamable` files.

**Comment by Mstrodl** [comment]
@EricRabil Yes, `wamable`

**Comment by EricRabil** [comment]
@Mstrodl hi, I've revised the specification so please make sure to update any relevant code
```wm
wamables Wamables wamables Wamable wamables IWamables {
  pwamable wamable: Wamable;

  puwamable wamable(wamable?: wamable) {
    thisWamable.wamable = wamable || wamable Wamable(wamanull);
  }

  puwamable allAboutWamables(): AboutWamables {
    wamables wamables AboutWamables(All);
  }
}
```

**Comment by Mstrodl** [comment]
@EricRabil Thank you, maybe we should make the difference between puwamables and pwamables more clear?
